namespace Gi7.Utils.ContentDetector
{
    public class HeaderSignature
    {
        public static HeaderSignature[] StockSignatures =
            new[]
            {
                new HeaderSignature {Signature = @"FFD8FFFE00", SignatureName = "JPG Graphic File", FileExtensions = new[] {@".JPEG", @".JPE", @".JPG"}},
                new HeaderSignature {Signature = @"FFD8FFE000", SignatureName = "JPG Graphic File", FileExtensions = new[] {@".JPEG", @".JPE", @".JPG"}},
                new HeaderSignature {Signature = @"474946383961", SignatureName = "GIF 89A", FileExtensions = new[] {@".gif"}},
                new HeaderSignature {Signature = @"474946383761", SignatureName = "GIF 87A", FileExtensions = new[] {@".gif"}},
                new HeaderSignature {Signature = @"424D", SignatureName = "Windows Bitmap", FileExtensions = new[] {@".bmp"}},
                new HeaderSignature {Signature = @"4D5A", SignatureName = "Executable File", FileExtensions = new[] {@".exe", @".com", @".386", @".ax", @".acm", @".sys", @".dll", @".drv", @".flt", @".fon", @".ocx", @".scr", @".lrc", @".vxd", @".cpl", @".x32"}},
                new HeaderSignature {Signature = @"504B0304", SignatureName = "Zip Compressed", FileExtensions = new[] {@".zip"}},
                new HeaderSignature {Signature = @"3A42617365", SignatureName = "", FileExtensions = new[] {@".cnt"}},
                new HeaderSignature {Signature = @"D0CF11E0A1B11AE1", SignatureName = "MS Compound Document v1 or Lotus Approach APR file", FileExtensions = new[] {@".doc", @".xls", @".xlt", @".ppt", @".apr"}},
                new HeaderSignature {Signature = @"0100000058000000", SignatureName = "", FileExtensions = new[] {@".emf"}},
                new HeaderSignature {Signature = @"03000000C466C456", SignatureName = "", FileExtensions = new[] {@".evt"}},
                new HeaderSignature {Signature = @"3F5F0300", SignatureName = "Windows Help File", FileExtensions = new[] {@".gid", @".hlp", @".lhp"}},
                new HeaderSignature {Signature = @"1F8B08", SignatureName = "GZ Compressed File", FileExtensions = new[] {@".gz"}},
                new HeaderSignature {Signature = @"28546869732066696C65", SignatureName = "", FileExtensions = new[] {@".hqx"}},
                new HeaderSignature {Signature = @"0000010000", SignatureName = "Icon File", FileExtensions = new[] {@".ico"}},
                new HeaderSignature {Signature = @"4C000000011402", SignatureName = "Windows Link File", FileExtensions = new[] {@".lnk"}},
                new HeaderSignature {Signature = @"25504446", SignatureName = "Adobe PDF File", FileExtensions = new[] {@".pdf"}},
                new HeaderSignature {Signature = @"5245474544495434", SignatureName = "", FileExtensions = new[] {@".reg"}},
                new HeaderSignature {Signature = @"7B5C727466", SignatureName = "Rich Text Format File", FileExtensions = new[] {@".rtf"}},
                new HeaderSignature {Signature = @"lh", SignatureName = "Lz compression file", FileExtensions = new[] {@".lzh"}},
                new HeaderSignature {Signature = @"25215053", SignatureName = "Adobe EPS File", FileExtensions = new[] {@".eps"}},
                new HeaderSignature {Signature = @"2112", SignatureName = "AIN Archive File", FileExtensions = new[] {@".ain"}},
                new HeaderSignature {Signature = @"1A02", SignatureName = "ARC/PKPAK Compressed 1", FileExtensions = new[] {@".arc"}},
                new HeaderSignature {Signature = @"1A03", SignatureName = "ARC/PKPAK Compressed 2", FileExtensions = new[] {@".arc"}},
                new HeaderSignature {Signature = @"1A04", SignatureName = "ARC/PKPAK Compressed 3", FileExtensions = new[] {@".arc"}},
                new HeaderSignature {Signature = @"1A08", SignatureName = "ARC/PKPAK Compressed 4", FileExtensions = new[] {@".arc"}},
                new HeaderSignature {Signature = @"1A09", SignatureName = "ARC/PKPAK Compressed 5", FileExtensions = new[] {@".arc"}},
                new HeaderSignature {Signature = @"60EA", SignatureName = "ARJ Compressed", FileExtensions = new[] {@".arj"}},
                new HeaderSignature {Signature = @"41564920", SignatureName = "Audio Video Interleave (AVI)", FileExtensions = new[] {@".avi"}},
                new HeaderSignature {Signature = @"425A68", SignatureName = "Bzip Archive", FileExtensions = new[] {@".bz", @".bz2"}},
                new HeaderSignature {Signature = @"49536328", SignatureName = "Cabinet File", FileExtensions = new[] {@".cab"}},
                new HeaderSignature {Signature = @"4C01", SignatureName = "Compiled Object Module", FileExtensions = new[] {@".obj"}},
                new HeaderSignature {Signature = @"303730373037", SignatureName = "CPIO Archive File", FileExtensions = new[] {@".tar", @".cpio"}},
                new HeaderSignature {Signature = @"4352555348", SignatureName = "CRUSH Archive File", FileExtensions = new[] {@".cru", @".crush"}},
                new HeaderSignature {Signature = @"3ADE68B1", SignatureName = "DCX Graphic File", FileExtensions = new[] {@".dcx"}},
                new HeaderSignature {Signature = @"1F8B", SignatureName = "Gzip Archive File", FileExtensions = new[] {@".gz", @".tar", @".tgz"}},
                new HeaderSignature {Signature = @"91334846", SignatureName = "HAP Archive File", FileExtensions = new[] {@".hap"}},
                new HeaderSignature {Signature = @"3C68746D6C3E", SignatureName = "HyperText Markup Language 1", FileExtensions = new[] {@".htm", @".html"}},
                new HeaderSignature {Signature = @"3C48544D4C3E", SignatureName = "HyperText Markup Language 2", FileExtensions = new[] {@".htm", @".html"}},
                new HeaderSignature {Signature = @"3C21444F4354", SignatureName = "HyperText Markup Language 3", FileExtensions = new[] {@".htm", @".html"}},
                new HeaderSignature {Signature = @"100", SignatureName = "ICON File", FileExtensions = new[] {@".ico"}},
                new HeaderSignature {Signature = @"5F27A889", SignatureName = "JAR Archive File", FileExtensions = new[] {@".jar"}},
                new HeaderSignature {Signature = @"2D6C68352D", SignatureName = "LHA Compressed", FileExtensions = new[] {@".lha"}},
                new HeaderSignature {Signature = @"20006040600", SignatureName = "Lotus 123 v1 Worksheet", FileExtensions = new[] {@".wk1", @".wks"}},
                new HeaderSignature {Signature = @"00001A0007800100", SignatureName = "Lotus 123 v3 FMT file", FileExtensions = new[] {@".fm3"}},
                new HeaderSignature {Signature = @"00001A0000100400", SignatureName = "Lotus 123 v3 Worksheet", FileExtensions = new[] {@".wk3"}},
                new HeaderSignature {Signature = @"20006800200", SignatureName = "Lotus 123 v4 FMT file", FileExtensions = new[] {@".fmt"}},
                new HeaderSignature {Signature = @"00001A0002100400", SignatureName = "Lotus 123 v5", FileExtensions = new[] {@".wk4"}},
                new HeaderSignature {Signature = @"5B7665725D", SignatureName = "Lotus Ami Pro", FileExtensions = new[] {@".ami"}},
                new HeaderSignature {Signature = @"300000041505052", SignatureName = "Lotus Approach ADX file", FileExtensions = new[] {@".adx"}},
                new HeaderSignature {Signature = @"1A0000030000", SignatureName = "Lotus Notes Database/Template", FileExtensions = new[] {@".nsf", @".ntf"}},
                new HeaderSignature {Signature = @"4D47582069747064", SignatureName = "Micrografix Designer 4", FileExtensions = new[] {@".ds4"}},
                new HeaderSignature {Signature = @"4D534346", SignatureName = "Microsoft CAB File Format", FileExtensions = new[] {@".cab"}},
                new HeaderSignature {Signature = @"4D546864", SignatureName = "Midi Audio File", FileExtensions = new[] {@".mid"}},
                new HeaderSignature {Signature = @"000001B3", SignatureName = "MPEG Movie", FileExtensions = new[] {@".mpg", @".mpeg"}},
                new HeaderSignature {Signature = @"0902060000001000B9045C00", SignatureName = "MS Excel v2", FileExtensions = new[] {@".xls"}},
                new HeaderSignature {Signature = @"0904060000001000F6055C00", SignatureName = "MS Excel v4", FileExtensions = new[] {@".xls"}},
                new HeaderSignature {Signature = @"7FFE340A", SignatureName = "MS Word", FileExtensions = new[] {@".doc"}},
                new HeaderSignature {Signature = @"1234567890FF", SignatureName = "MS Word 6.0", FileExtensions = new[] {@".doc"}},
                new HeaderSignature {Signature = @"31BE000000AB0000", SignatureName = "MS Word for DOS 6.0", FileExtensions = new[] {@".doc"}},
                new HeaderSignature {Signature = @"1A00000300001100", SignatureName = "Notes Database", FileExtensions = new[] {@".nsf"}},
                new HeaderSignature {Signature = @"7E424B00", SignatureName = "PaintShop Pro Image File", FileExtensions = new[] {@".psp"}},
                new HeaderSignature {Signature = @"504B0304", SignatureName = "PKZIP Compressed", FileExtensions = new[] {@".zip"}},
                new HeaderSignature {Signature = @"89504E470D0A", SignatureName = "PNG Image File", FileExtensions = new[] {@".png"}},
                new HeaderSignature {Signature = @"6D646174", SignatureName = "QuickTime Movie", FileExtensions = new[] {@".mov"}},
                new HeaderSignature {Signature = @"6D646174", SignatureName = "Quicktime Movie File", FileExtensions = new[] {@".qt"}},
                new HeaderSignature {Signature = @"52617221", SignatureName = "RAR Archive File", FileExtensions = new[] {@".rar"}},
                new HeaderSignature {Signature = @"2E7261FD", SignatureName = "Real Audio File", FileExtensions = new[] {@".ra", @".ram"}},
                new HeaderSignature {Signature = @"EDABEEDB", SignatureName = "RPM Archive File", FileExtensions = new[] {@".rpm"}},
                new HeaderSignature {Signature = @"2E736E64", SignatureName = "SoundMachine Audio File", FileExtensions = new[] {@".au"}},
                new HeaderSignature {Signature = @"53495421", SignatureName = "Stuffit v1 Archive File", FileExtensions = new[] {@".sit"}},
                new HeaderSignature {Signature = @"53747566664974", SignatureName = "Stuffit v5 Archive File", FileExtensions = new[] {@".sit"}},
                new HeaderSignature {Signature = @"1F9D", SignatureName = "TAR Compressed Archive File", FileExtensions = new[] {@".z"}},
                new HeaderSignature {Signature = @"49492A", SignatureName = "TIFF (Intel)", FileExtensions = new[] {@".tif", @".tiff"}},
                new HeaderSignature {Signature = @"4D4D2A", SignatureName = "TIFF (Motorola)", FileExtensions = new[] {@".tif", @".tiff"}},
                new HeaderSignature {Signature = @"554641", SignatureName = "UFA Archive File", FileExtensions = new[] {@".ufa"}},
                new HeaderSignature {Signature = @"57415645666D74", SignatureName = "Wave Files", FileExtensions = new[] {@".wav"}},
                new HeaderSignature {Signature = @"D7CDC69A", SignatureName = "Windows Meta File", FileExtensions = new[] {@".wmf"}},
                new HeaderSignature {Signature = @"4C000000", SignatureName = "Windows Shortcut (Link File)", FileExtensions = new[] {@".lnk"}},
                new HeaderSignature {Signature = @"504B3030504B0304", SignatureName = "WINZIP Compressed", FileExtensions = new[] {@".zip"}},
                new HeaderSignature {Signature = @"FF575047", SignatureName = "WordPerfect Graphics", FileExtensions = new[] {@".wpg"}},
                new HeaderSignature {Signature = @"FF575043", SignatureName = "WordPerfect v5 or v6", FileExtensions = new[] {@".wp"}},
                new HeaderSignature {Signature = @"3C3F786D6C", SignatureName = "XML Document", FileExtensions = new[] {@".xml"}},
                new HeaderSignature {Signature = @"FFFE3C0052004F004F0054005300540055004200", SignatureName = "XML Document (ROOTSTUB)", FileExtensions = new[] {@".xml"}},
                new HeaderSignature {Signature = @"3C21454E54495459", SignatureName = "XML DTD", FileExtensions = new[] {@".dtd"}},
                new HeaderSignature {Signature = @"5A4F4F20", SignatureName = "ZOO Archive File", FileExtensions = new[] {@".zoo"}},
                new HeaderSignature {Signature = @"01766F72626973", SignatureName = "Ogg Vorbis", FileExtensions = new[] {@".ogg"}},
            };

        public string SignatureName { get; set; }

        public string[] FileExtensions { get; set; }

        public string Signature { get; set; }
    }
}